swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger ReST Article
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /course:
    get:
      operationId: course.read_all
      tags:
        - course
      summary: Read the entire list of course
      description: Read the list of course
      parameters:
        - name: length
          in: query
          type: integer
          description: Number of course to get from course
          required: false
        - name: offset
          in: query
          type: integer
          description: Offset from beginning of list where to start gathering course
          required: false
      responses:
        200:
          description: Successfully read course list operation
          schema:
            type: array
            items:
              properties:
                fname:
                  type: string
                lname:
                  type: string
                timestamp:
                  type: string

    post:
      operationId: course.create
      tags:
        - course
      summary: Create a person and add it to the course list
      description: Create a new person in the course list
      parameters:
        - name: person
          in: body
          description: Person to create
          required: True
          schema:
            type: object
            properties:
              fname:
                type: string
                description: First name of person to create
              lname:
                type: string
                description: Last name of person to create
      responses:
        201:
          description: Successfully created person in list

  /course/{lname}:
    get:
      operationId: course.read_one
      tags:
        - course
      summary: Read one person from the course list
      description: Read one person from the course list
      parameters:
        - name: lname
          in: path
          description: Last name of the person to get from the list
          type: string
          required: True
      responses:
        200:
          description: Successfully read person from course list operation
          schema:
            properties:
              fname:
                type: string
              lname:
                type: string
              timestamp:
                type: string

    put:
      operationId: course.update
      tags:
        - course
      summary: Update a person in the course list
      description: Update a person in the course list
      parameters:
        - name: lname
          in: path
          description: Last name of the person to update in the list
          type: string
          required: True
        - name: person
          in: body
          schema:
            type: object
            properties:
              fname:
                type: string
              lname:
                type: string
      responses:
        200:
          description: Successfully updated person in course list

    delete:
      operationId: course.delete
      tags:
        - course
      summary: Delete a person from the course list
      description: Delete a person
      parameters:
        - name: lname
          in: path
          type: string
          required: True
      responses:
        200:
          description: Successfully deleted a person from course list